workflows:
  version: 2
  pipline:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

version: 2
jobs:
  build:
    environment:
      REDISTOGO_URL: "redis://localhost:6379"

    docker:
      - image: cimg/ruby:2.7-browsers
        environment:
            BUNDLER_VERSION: 2.1.4
      - image: circleci/postgres:12.3
      - image: redis

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install postgres client
          command: |
            sudo apt update
            sudo apt install postgresql-client

      - run:
          name: Wait for Redis to receive connections
          command: dockerize -wait tcp://localhost:6379 -timeout 1m

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            gem install bundler -v 2.1.4

            bundle config git.allow_insecure true

            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: |
            bundle exec hanami db prepare

      # run tests!
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results

            bundle exec rspec

      - run:
          name: run rubocop
          command: |
            bundle exec rubocop

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

  deploy:
    docker:
      - image: cimg/ruby:2.7-browsers
      - image: circleci/postgres:12.3

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
